// Generated by `bun run db:generate`. Do not edit by hand.
// Embeds every committed migration so a compiled binary carries its own schema history.
import m0 from './migrations/0000_sudden_nextwave.sql' with { type: 'text' };
import m1 from './migrations/0001_jittery_the_initiative.sql' with { type: 'text' };

export interface EmbeddedMigration {
    /** drizzle-kit's file tag, e.g. `0000_faithful_gorgon`. */
    tag: string;
    /** Journal timestamp, stored as `created_at` in `__drizzle_migrations`. */
    when: number;
    sql: string;
}

export const MIGRATIONS: EmbeddedMigration[] = [
    { tag: '0000_sudden_nextwave', when: 1785555642242, sql: m0 },
    { tag: '0001_jittery_the_initiative', when: 1785572543174, sql: m1 },
];
