/**
 * Regenerates `src/db/migrations.generated.ts` from whatever `drizzle-kit
 * generate` just wrote. Run as part of `bun run db:generate`.
 *
 * The barrel exists so migration SQL is embedded in the compiled binary instead
 * of being read off disk at boot — see the note in `src/db/migrate.ts`.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const dbDir = resolve(import.meta.dir, '..', 'src', 'db');
const migrationsDir = join(dbDir, 'migrations');
const journalPath = join(migrationsDir, 'meta', '_journal.json');
const outPath = join(dbDir, 'migrations.generated.ts');

interface JournalEntry {
    idx: number;
    when: number;
    tag: string;
}

let entries: JournalEntry[] = [];
try {
    const journal = JSON.parse(readFileSync(journalPath, 'utf8')) as { entries: JournalEntry[] };
    entries = [...journal.entries].sort((a, b) => a.idx - b.idx);
} catch {
    console.warn(`no migration journal at ${journalPath} — writing an empty barrel`);
}

for (const entry of entries) {
    const file = `${entry.tag}.sql`;
    if (!readdirSync(migrationsDir).includes(file)) {
        throw new Error(`journal lists ${entry.tag} but ${file} is missing from ${migrationsDir}`);
    }
}

const imports = entries.map((e, i) => `import m${i} from './migrations/${e.tag}.sql' with { type: 'text' };`);
const rows = entries.map((e, i) => `    { tag: '${e.tag}', when: ${e.when}, sql: m${i} },`);

const banner = `// Generated by \`bun run db:generate\`. Do not edit by hand.
// Embeds every committed migration so a compiled binary carries its own schema history.
`;

const body = `${banner}${imports.length > 0 ? `${imports.join('\n')}\n` : ''}
export interface EmbeddedMigration {
    /** drizzle-kit's file tag, e.g. \`0000_faithful_gorgon\`. */
    tag: string;
    /** Journal timestamp, stored as \`created_at\` in \`__drizzle_migrations\`. */
    when: number;
    sql: string;
}

export const MIGRATIONS: EmbeddedMigration[] = [
${rows.join('\n')}${rows.length > 0 ? '\n' : ''}];
`;

writeFileSync(outPath, body);
console.log(`embedded ${entries.length} migration(s) into ${outPath}`);
