/**
 * Every clinic server address is plain `http://` on the tailnet: Tailscale is
 * the transport and the security boundary (SPEC §1), so there is no TLS to
 * terminate. Android refuses cleartext HTTP from a release build unless the
 * main manifest allows it.
 *
 * The debug manifest Expo generates already allows it, which is why a dev build
 * connects and a release build never reached any server at all. The
 * `android.usesCleartextTraffic` key that used to sit in `app.json` is not one
 * Expo reads, and `android/` is regenerated by prebuild, so this has to be a
 * config plugin.
 */
const { AndroidConfig, withAndroidManifest } = require('expo/config-plugins');

function allowCleartext(manifest) {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(manifest);
    application.$['android:usesCleartextTraffic'] = 'true';
    return manifest;
}

module.exports = function withCleartextTraffic(config) {
    return withAndroidManifest(config, (cfg) => {
        cfg.modResults = allowCleartext(cfg.modResults);
        return cfg;
    });
};

module.exports.allowCleartext = allowCleartext;
