/**
 * A dev build installs as `com.lustre.clinic.dev`, under its own launcher name,
 * so it sits beside the clinic's release on one phone. Without it Android sees
 * one package signed two ways and refuses the second install — "package already
 * exists" — and the only way past is uninstalling the build you were comparing
 * against.
 *
 * It is Gradle's `applicationIdSuffix` on the debug build type rather than a
 * different `android.package`, so which APK it is decides: `assembleRelease` is
 * the clinic's id whatever the environment holds, one prebuild serves both, and
 * there is no flag to put back before a release.
 *
 * `namespace` is left alone — it names the Java package `MainActivity` and the
 * R class live in, which both builds share. That is why `expo run:android` has
 * to be told `--app-id com.lustre.clinic.dev` (`scripts/device.sh` and the two
 * beside it do): it otherwise launches the id it reads out of Gradle, which is
 * the unsuffixed one.
 *
 * The launcher name is a `strings.xml` in the debug source set, which overrides
 * the one prebuild writes into `main`. A Gradle `resValue` would collide with
 * that file rather than win over it.
 *
 * `android/` is regenerated by prebuild, hence a config plugin.
 */
const fs = require('node:fs/promises');
const path = require('node:path');
const { withAppBuildGradle, withDangerousMod } = require('expo/config-plugins');

const MARKER = '// @lustre: dev application id (plugins/withDevIdentity.js)';

const APPLICATION_ID_SUFFIX = '.dev';
const DEV_APP_NAME = 'Lustre Clinic (DEV)';

// The first `debug {` inside `buildTypes` — not the one in `signingConfigs`,
// which sits above it and outside the match.
const DEBUG_BUILD_TYPE = /(buildTypes\s*\{[^}]*?debug\s*\{[^\S\n]*\r?\n)/;

function applyDevApplicationId(contents) {
    if (contents.includes(MARKER)) return contents;

    // Silently leaving the suffix out would put both builds back on one id and
    // bring the failed install back with them.
    if (!DEBUG_BUILD_TYPE.test(contents)) {
        throw new Error(
            `withDevIdentity: app/build.gradle no longer matches ${DEBUG_BUILD_TYPE}. The prebuild template changed; update the plugin.`,
        );
    }

    return contents.replace(
        DEBUG_BUILD_TYPE,
        (match) =>
            `${match}            ${MARKER}\n            applicationIdSuffix '${APPLICATION_ID_SUFFIX}'\n`,
    );
}

/** Relative to `android/`. */
const DEV_STRINGS_PATH = path.join('app', 'src', 'debug', 'res', 'values', 'strings.xml');

const DEV_STRINGS_XML = `<?xml version="1.0" encoding="utf-8"?>
<resources>
  <string name="app_name">${DEV_APP_NAME}</string>
</resources>
`;

module.exports = function withDevIdentity(config) {
    const suffixed = withAppBuildGradle(config, (cfg) => {
        cfg.modResults.contents = applyDevApplicationId(cfg.modResults.contents);
        return cfg;
    });

    return withDangerousMod(suffixed, [
        'android',
        async (cfg) => {
            const file = path.join(cfg.modRequest.platformProjectRoot, DEV_STRINGS_PATH);
            await fs.mkdir(path.dirname(file), { recursive: true });
            await fs.writeFile(file, DEV_STRINGS_XML);
            return cfg;
        },
    ]);
};

module.exports.applyDevApplicationId = applyDevApplicationId;
module.exports.APPLICATION_ID_SUFFIX = APPLICATION_ID_SUFFIX;
module.exports.DEV_APP_NAME = DEV_APP_NAME;
module.exports.DEV_STRINGS_PATH = DEV_STRINGS_PATH;
module.exports.DEV_STRINGS_XML = DEV_STRINGS_XML;
