/**
 * Release APKs are signed with the clinic's own keystore, never the public debug
 * key prebuild writes in. Android installs an update only over an app signed
 * with the same key, and the one way past a mismatch is an uninstall, which
 * wipes the saved server address, the role and the cached schedule. `android/`
 * is regenerated by prebuild, hence a config plugin.
 *
 * The keystore path, alias and passwords are Gradle properties, read from
 * `~/.gradle/gradle.properties` or `ORG_GRADLE_PROJECT_<name>` in the
 * environment, so none of it is in the repo (infra/README.md, "Release
 * signing"). A release build without them stops and names what is missing
 * rather than falling back to the debug key. Debug builds never read them.
 */
const { withAppBuildGradle } = require('expo/config-plugins');

const MARKER = '// @lustre: release signing (plugins/withReleaseSigning.js)';

const PROPERTIES = [
    'LUSTRE_RELEASE_STORE_FILE',
    'LUSTRE_RELEASE_STORE_PASSWORD',
    'LUSTRE_RELEASE_KEY_ALIAS',
    'LUSTRE_RELEASE_KEY_PASSWORD',
];

// Checked once the task graph is known, not while configuring, so an
// `assembleDebug` on a machine with no keystore is untouched.
const PREAMBLE = `${MARKER}
def lustreSigning = [${PROPERTIES.map((name) => `'${name}'`).join(', ')}].collectEntries { [(it): findProperty(it)] }
def lustreSigningMissing = lustreSigning.findAll { !it.value }.collect { it.key }
def lustreSigningProblem = null
if (!lustreSigningMissing.isEmpty()) {
    lustreSigningProblem = "these Gradle properties are not set: \${lustreSigningMissing.join(', ')}"
} else if (!file(lustreSigning.LUSTRE_RELEASE_STORE_FILE).exists()) {
    lustreSigningProblem = "there is no keystore at \${lustreSigning.LUSTRE_RELEASE_STORE_FILE}"
}
gradle.taskGraph.whenReady { graph ->
    if (lustreSigningProblem && graph.allTasks.any { it.project == project && it.name.contains('Release') }) {
        throw new GradleException("A release build is signed with the Lustre release keystore, and \${lustreSigningProblem}. Set them in ~/.gradle/gradle.properties (infra/README.md, Release signing). Refusing to fall back to the debug key.")
    }
}
`;

const RELEASE_SIGNING_CONFIG = `        release {
            if (!lustreSigningProblem) {
                storeFile file(lustreSigning.LUSTRE_RELEASE_STORE_FILE)
                storePassword lustreSigning.LUSTRE_RELEASE_STORE_PASSWORD
                keyAlias lustreSigning.LUSTRE_RELEASE_KEY_ALIAS
                keyPassword lustreSigning.LUSTRE_RELEASE_KEY_PASSWORD
            }
        }
`;

const RELEASE_BUILD_TYPE = /(buildTypes\s*\{[\s\S]*?release\s*\{[^}]*?signingConfig\s+)signingConfigs\.debug/;
const SIGNING_CONFIGS = /signingConfigs\s*\{\n/;
const ANDROID_BLOCK = /\nandroid\s*\{/;

function applyReleaseSigning(contents) {
    if (contents.includes(MARKER)) return contents;

    // A template that no longer has these would otherwise be left signing with
    // the debug key, which is the failure this plugin exists to prevent.
    for (const pattern of [RELEASE_BUILD_TYPE, SIGNING_CONFIGS, ANDROID_BLOCK]) {
        if (!pattern.test(contents)) {
            throw new Error(
                `withReleaseSigning: app/build.gradle no longer matches ${pattern}. The prebuild template changed; update the plugin.`,
            );
        }
    }

    return contents
        .replace(RELEASE_BUILD_TYPE, '$1signingConfigs.release')
        .replace(SIGNING_CONFIGS, (match) => `${match}${RELEASE_SIGNING_CONFIG}`)
        .replace(ANDROID_BLOCK, (match) => `\n${PREAMBLE}${match}`);
}

module.exports = function withReleaseSigning(config) {
    return withAppBuildGradle(config, (cfg) => {
        cfg.modResults.contents = applyReleaseSigning(cfg.modResults.contents);
        return cfg;
    });
};

module.exports.applyReleaseSigning = applyReleaseSigning;
module.exports.PROPERTIES = PROPERTIES;
