/**
 * `packages/app/android/` is generated by `expo prebuild` and gitignored, so
 * edits to the generated `gradle.properties` are lost on the next regeneration.
 * These four settings have to survive that, hence a config plugin.
 *
 * They exist because the default build is sized for a CI box, not a 16 GB
 * laptop running the emulator, the API server and the bundler at once:
 *
 * - reactNativeArchitectures: the default builds all four ABIs — four native
 *   compiles and links to produce three slices nothing here installs. The
 *   value below is only a default; `scripts/device.sh` and `scripts/emulator.sh`
 *   export ORG_GRADLE_PROJECT_reactNativeArchitectures with the ABI the
 *   attached device actually reports, and that env var wins over this file.
 * - workers.max: Gradle defaults to the core count, which is enough concurrent
 *   JVMs and link steps to exhaust memory.
 */
const { withGradleProperties } = require('expo/config-plugins');

const PROPERTIES = [
    { key: 'reactNativeArchitectures', value: 'x86_64' },
    { key: 'org.gradle.jvmargs', value: '-Xmx1536m -XX:MaxMetaspaceSize=512m' },
    { key: 'org.gradle.workers.max', value: '3' },
    { key: 'kotlin.daemon.jvmargs', value: '-Xmx1024m' },
];

function applyProperties(items) {
    const next = [...items];
    for (const { key, value } of PROPERTIES) {
        const existing = next.find((item) => item.type === 'property' && item.key === key);
        if (existing) {
            existing.value = value;
        } else {
            next.push({ type: 'property', key, value });
        }
    }
    return next;
}

module.exports = function withBuildTuning(config) {
    return withGradleProperties(config, (cfg) => {
        cfg.modResults = applyProperties(cfg.modResults);
        return cfg;
    });
};

module.exports.applyProperties = applyProperties;
module.exports.PROPERTIES = PROPERTIES;
