/**
 * The system navigation bar reads as part of the tab bar, not a grey strip
 * under it. `edgeToEdgeEnabled` already makes the bar transparent and the tab
 * bar paints its canvas behind it (`BottomTabBar`, `insets.bottom`), but on
 * three-button navigation Android then lays its own translucent scrim over that
 * area "for contrast", so the buttons sat on a different colour than the app.
 * Turning `enforceNavigationBarContrast` off in the app theme removes the scrim.
 *
 * With the scrim gone the buttons sit straight on the light canvas, so they are
 * drawn dark (`windowLightNavigationBar`), the same way the status bar's icons
 * are (`<StatusBar style="dark" />` in `App.tsx`).
 *
 * `android/` is regenerated by prebuild, so this has to be a config plugin.
 */
const { AndroidConfig, withAndroidStyles } = require('expo/config-plugins');

const ITEMS = {
    'android:enforceNavigationBarContrast': 'false',
    'android:windowLightNavigationBar': 'true',
};

function styleNavigationBar(styles) {
    let next = styles;
    for (const [name, value] of Object.entries(ITEMS)) {
        next = AndroidConfig.Styles.assignStylesValue(next, {
            add: true,
            parent: AndroidConfig.Styles.getAppThemeGroup(),
            name,
            value,
        });
    }
    return next;
}

module.exports = function withNavigationBarContrast(config) {
    return withAndroidStyles(config, (cfg) => {
        cfg.modResults = styleNavigationBar(cfg.modResults);
        return cfg;
    });
};

module.exports.styleNavigationBar = styleNavigationBar;
